### ISSUE TITLE
Checklist for being usable by others

### ISSUE THREAD

**Issue by kneasle** [kneasle/monument#3]
- [x] Create Monument/Bellframe/Jigsaw monorepo so code can be built reliably.  Also allows tests to be run in CI.
- [ ] Document the input format properly (looking at Cargo for inspiration?)
- [ ] Add default music scoring?
- [ ] Fix obscene memory usage or add warning (we can probably fix this at the same time as adding proper multithreading)
- [ ] Possibly re-implement `./to-complib.py` into Rust?  Or at least make it more helpful if `pyperclip` isn't installed.  If we want to parse insertable blocks, then this'd be useful anyway.

**Comment by kneasle** [comment]
Moving to [kneasle/ringing-monorepo](github.com/kneasle/ringing-monorepo), so this issue is being closed.
